# Umbrella Infrastructure {#umbrella}

## Physical Hardware and Subscriptions

- One Github organization (http://github.com/folkehelseinstituttet/)
- One Github team (https://github.com/orgs/folkehelseinstituttet/teams/dashboards)
- One [drat](https://github.com/eddelbuettel/drat) repository (https://folkehelseinstituttet.github.io/drat/)
- One travis-ci.org account (http://travis-ci.org/folkehelseinstituttet)
- One travis-ci.com account (http://travis-ci.com/folkehelseinstituttet)
- One Docker hub account (http://hub.docker.com/u/raw996/)
- At least three computers:
    1. Production linux computer `smhb`
    2. Integration testing linux computer `linux`
    3. Development linux computers (1 per person)

### Requirements - smhb

- Git
- Docker Engine - Community (https://www.docker.com/products/docker-engine)

### Requirements - linux

- Git
- Docker Engine - Community (https://www.docker.com/products/docker-engine)
- Jenkins installed via a Docker container (http://jenkins.io)

### Requirements - dev

- Git
- Docker Engine - Community (https://www.docker.com/products/docker-engine)

## Configuration, Scripts, etc.

Most of the bash scripts, Docker files, passwords, etc. are all hosted at the private Github repository [raubreywhite/dashboards_control](https://github.com/raubreywhite/dashboards_control).

```
- $DASHBOARDS_FOLDER/dashboards_control/
  |-- bin/
    |-- dev_down.sh
    |-- dev_up.sh
    |-- docker_build.sh
    |-- docker_login.sh
    |-- docker_push_test_to_prod.sh
    |-- prod_down.sh
    |-- prod_up.sh
    |-- prod_update.sh
    |-- public.sh
    |-- test_noispiah.sh
    |-- test_normomo.sh
    |-- test_sykdomspuls_log.sh
    |-- test_sykdomspuls_pdf.sh
    |-- test_sykdomspuls.sh
  |-- infrastructure/
    |-- dashboards_nginx/
    |-- dashboards_r/
      |-- add_autofs.sh
      |-- add_cron.sh
      |-- auto.mounts
      |-- crontab
      |-- Dockerfile
      |-- emails_sykdomspuls_alert_test.xlsx
      |-- emails_sykdomspuls_alert.xlsx
      |-- emails.xlsx
      |-- httr-oauth_2017_09_17
      |-- mail.json
      |-- repo-key
      |-- secret.sh
    |-- dashboards_shiny/
    |-- docker-compose-api.yml
    |-- docker-compose-dev.yml
    |-- docker-compose-prod.yml
    |-- docker-compose-test.yml
```

### $DASHBOARDS_FOLDER/dashboards_control/bin/dev_down.sh

Dev script to shut down docker-compose

### $DASHBOARDS_FOLDER/dashboards_control/bin/dev_up.sh

Dev script to start docker-compose

### $DASHBOARDS_FOLDER/dashboards_control/bin/docker_build.sh

Builds all relevant Docker containers

### $DASHBOARDS_FOLDER/dashboards_control/bin/docker_login.sh

Logs in to docker-hub

### $DASHBOARDS_FOLDER/dashboards_control/bin/docker_push_test_to_prod.sh 

Retags 'test' Docker containers to 'production' and pushs them to docker-hub

### $DASHBOARDS_FOLDER/dashboards_control/bin/prod_down.sh

Only to be used on the production computer `smhb`. This bash script stops the docker-compose.

Note: This script is not used.

### $DASHBOARDS_FOLDER/dashboards_control/bin/prod_up.sh

Only to be used on the production computer `smhb`. This bash script starts up the docker-compose.

Note: This script is not used.
    
### $DASHBOARDS_FOLDER/dashboards_control/bin/prod_update.sh

Only to be used on the production computer `smhb`. This bash script:

1. Removes unused Docker container/images (important so we don't run out of space)
2. Runs some scripts required for network access
3. Pulls the latest version of [raubreywhite/dashboards_control](https://github.com/raubreywhite/dashboards_control)
4. Stops the [docker-compose-prod.yml](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/docker-compose-prod.yml)
5. Pulls the latest production images for:
    - [raw996/dashboards_r:production](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/Dockerfile)
    - [raw996/dashboards_nginx:production](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_nginx/Dockerfile)
    - [raw996/dashboards_shiny:production](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_shiny/Dockerfile)
6. Starts the [docker-compose-prod.yml](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/docker-compose-prod.yml)

### $DASHBOARDS_FOLDER/dashboards_control/bin/public.sh

Lists a bunch of environmental variables

### $DASHBOARDS_FOLDER/dashboards_control/bin/test_noispiah.sh {#test_noispiah}

Runs `/r/noispiah/src/RunTest.R` inside [raw996/dashboards_r:test](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/Dockerfile)

Note: This script is generally only run by `Jenkins` on `linux` as the integration testing for [noispiah](https://folkehelseinstituttet.github.io/dashboards_noispiah/).

### $DASHBOARDS_FOLDER/dashboards_control/bin/test_normomo.sh

Runs `/r/normomo/src/RunTest.R` inside [raw996/dashboards_r:test](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/Dockerfile)

Note: This script is generally only run by `Jenkins` on `linux` as the integration testing for [normomo](https://folkehelseinstituttet.github.io/dashboards_normomo/).

### $DASHBOARDS_FOLDER/dashboards_control/bin/test_sykdomspuls_log.sh

Runs `/r/sykdomspulslog/src/RunTest.R` inside [raw996/dashboards_r:test](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/Dockerfile)

Note: This script is generally only run by `Jenkins` on `linux` as the integration testing for [sykdomspuls_log](https://folkehelseinstituttet.github.io/dashboards_sykdomspuls_log/).

### $DASHBOARDS_FOLDER/dashboards_control/bin/test_sykdomspuls_pdf.sh

Runs `/r/sykdomspulspdf/src/RunTest.R` inside [raw996/dashboards_r:test](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/Dockerfile)

Note: This script is generally only run by `Jenkins` on `linux` as the integration testing for [sykdomspuls_pdf](https://folkehelseinstituttet.github.io/dashboards_sykdomspuls_pdf/).

### $DASHBOARDS_FOLDER/dashboards_control/bin/test_sykdomspuls.sh

Runs `/r/sykdomspuls/src/RunTest.R` inside [raw996/dashboards_r:test](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/Dockerfile)

Note: This script is generally only run by `Jenkins` on `linux` as the integration testing for [sykdomspuls](https://folkehelseinstituttet.github.io/dashboards_sykdomspuls/).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/add_autofs.sh

See [autofs](#autofs).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/add_cron.sh

See [cron](#cron).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/auto.mounts

See [autofs](#autofs).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/crontab

See [cron](#cron).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/Dockerfile

See [here](#analysisdocker).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/emails_sykdomspuls_alert_test.xlsx

A list of email addresses used in [sykdomspuls](https://folkehelseinstituttet.github.io/dashboards_sykdomspuls/).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/emails_sykdomspuls_alert.xlsx

A list of email addresses used in [sykdomspuls](https://folkehelseinstituttet.github.io/dashboards_sykdomspuls/).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/emails.xlsx

A list of email addresses used in many projects.

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/httr-oauth_2017_09_17 {#httroauth}

The authorization file for the dashboardsfhi@gmail.com. This probably needs to be refreshed every year??

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/mail.json

Related to [httr-oauth](#httroauth).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/repo-key

The repo-key for downloading the private [raubreywhite/dashboards_control](https://github.com/raubreywhite/dashboards_control) repository.

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/dashboards_r/secret.sh

Passwords.

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/docker-compose-api.yml

Docker-compose file used for testing the [API](https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/blob/master/inst/src/RunAPI.R).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/docker-compose-dev.yml

Docker-compose file used for development. See [here](#dockercompose).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/docker-compose-prod.yml

Docker-compose file used for the production computer. See [here](#dockercompose).

### $DASHBOARDS_FOLDER/dashboards_control/infrastructure/docker-compose-test.yml

Docker-compose file used for integration testing of `Jenkins` on `linux`. See [here](#dockercompose).

## Analysis Docker Image {#analysisdocker}

### Images

Our analysis Docker images are based off the [rocker](https://rocker-project.org) images. More specifically, the [rocker/verse:3.5.0](https://hub.docker.com/r/rocker/verse/) image.

This Docker image is then expanded upon by a separate Dockerfile [raw996/dhadley](https://github.com/raubreywhite/docker/blob/master/dhadley/Dockerfile). This Docker image is automatically rebuilt by `Jenkins` on `linux` whenever the repository is updated. The resultant Docker image is pushed to [raw996/dhadley:3.5.0](https://hub.docker.com/r/raw996/dhadley/). This image is a general-purpose analysis image, with no sensitive information in it.

This Docker image is then expanded upon by a separate Dockerfile [raw996/dashboards_r](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/Dockerfile). This Docker image is automatically rebuilt by `Jenkins` on `linux` whenever the repository is updated. The resultant Docker image is locally tagged as `raw996/dashboards_r:test` and then a number of integration tests are performed on it. If the integration tests are passed, then the Docker image is retagged and pushed to [raw996/dashboards_r:production](https://hub.docker.com/r/raw996/dashboards_r/). This image is private as it contains passwords and email addresses.

### Automated Analysis R Packages

#travis

### File Structure {#internalfilestructure}

Inside `raw996/dashboards_r` we have the following file structure:

```
/data_raw/
  |-- normomo/
  |-- noispiah/
  |-- sykdomspuls/
  |-- sykdomspuls_pdf/
  |-- sykdomspuls_log/
/data_clean/
  |-- normomo/
  |-- noispiah/
  |-- sykdomspuls/
  |-- sykdomspuls_pdf/
  |-- sykdomspuls_log/
/data_app/
  |-- normomo/
  |-- noispiah/
  |-- sykdomspuls/
  |-- sykdomspuls_pdf/
  |-- sykdomspuls_log/
/results/
  |-- normomo/
  |-- noispiah/
  |-- sykdomspuls/
  |-- sykdomspuls_pdf/
  |-- sykdomspuls_log/
/usr/local/lib/R/site-library/  <soft linked to /r>
  |-- <OTHER R PACKAGES INSTALLED HERE>/
  |-- fhi/
  |-- normomo/
  |-- noispiah/
  |-- sykdomspuls/
  |-- sykdomspuls_pdf/
  |-- sykdomspuls_log/
  |-- <OTHER R PACKAGES INSTALLED HERE>/
```

Note that we have a soft link between `/r` and `/usr/local/lib/R/site-library/`.

### cron {#cron}

We use [cron](https://en.wikipedia.org/wiki/Cron) to schedule the analyses. The schedule is specified in [crontab](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/crontab).

The cronjobs are only activated when the environmental variable `ADD=cron` is defined. Cronjobs are then activated through [add_cron.sh](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/add_cron.sh).

In principle, cronjobs should only be activated on `smhb`.

### autofs {#autofs}

We use [autofs](https://help.ubuntu.com/community/Autofs) to connect to the F network. The network locations, username, and password are specified in [auto.mounts](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/auto.mounts).

Autofs is only activated when the environmental variable `ADD_AUTOFS=yes` is defined. Autofs is then activated through [add_autofs.sh](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_r/add_autofs.sh).

In principle, autofs should only be activated on `smhb`.

## Reverse Proxy Docker Image

We use nginx as a reverse proxy to make rstudio server available to the developers.

The relevant Dockerfile is [here](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/dashboards_nginx/Dockerfile) and is pushed to [raw996/dashboards_nginx:production](https://hub.docker.com/r/raw996/dashboards_nginx/) after integration testing is passed.

## Docker Compose {#dockercompose}

[Docker compose](https://docs.docker.com/compose/) is used to integrate these Docker images into the local filesystem. We have multiple docker-compose files for different reasons:

- For [production](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/docker-compose-prod.yml) on `smhb`
- For [testing](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/docker-compose-test.yml) on `linux`
- For [development](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/docker-compose-dev.yml) on a dev computer

## Production Computer - smhb

### crontab

```
# m h  dom mon dow   command
5 1 * * * /home/raw996/git/dashboards_control/bin/prod_update.sh
@reboot /home/raw996/git/dashboards_control/bin/prod_update.sh
```

### File Structure

```
/home/raw996/git/dashboards_control/
```

### Explanation

`smhb` is designed to be extremely simple. It has two jobs:

1. Updating [raw996/dashboards_r:production](https://hub.docker.com/r/raw996/dashboards_r/), [raw996/dashboards_shiny:production](https://hub.docker.com/r/raw996/dashboards_shiny/), and [raw996/dashboards_nginx:production](https://hub.docker.com/r/raw996/dashboards_nginx/)
2. Making sure that [docker-compose-prod.yml](https://github.com/raubreywhite/dashboards_control/blob/master/infrastructure/docker-compose-prod.yml) is running

We purposefully minimize all integration with the base machine, because this enables us to be deploy-environment independent and to move our deployment anywhere with minimal hassle.

## Integration Testing Computer - linux {#integrationtesting}

### File Structure

```
/home/raw996/
  |-- docker-compose-jenkins/
    |-- docker-compose.yml
  |-- data/
    |-- data_app/
      |-- normomo/
      |-- sykdomspuls/
    |-- data_clean/
      |-- normomo/
      |-- sykdomspuls/
    |-- data_raw/
      |-- normomo/
        |-- FHIDOD2_20170425.txt
      |-- sykdomspuls/
        |-- partially_formatted_2017_08_01.txt
    |-- data_results/
      |-- normomo/
      |-- sykdomspuls/
  |-- jenkins/
```

### Explanation

`linux` has three jobs:

1. Building [raw996/dhadley](https://github.com/raubreywhite/docker/blob/master/dhadley/Dockerfile
2. Integration testing for the automated analyses
3. Pushing [raw996/dashboards_r:production](https://hub.docker.com/r/raw996/dashboards_r/), [raw996/dashboards_shiny:production](https://hub.docker.com/r/raw996/dashboards_shiny/), and [raw996/dashboards_nginx:production](https://hub.docker.com/r/raw996/dashboards_nginx/) to Docker hub after successful integration testing

Integration testing happens by Jenkins running:

- [test_noispiah.sh](https://github.com/raubreywhite/dashboards_control/blob/master/bin/test_noispiah.sh)
- [test_normomo.sh](https://github.com/raubreywhite/dashboards_control/blob/master/bin/test_normomo.sh)
- [test_sykdomspuls.sh](https://github.com/raubreywhite/dashboards_control/blob/master/bin/test_sykdomspuls.sh)
- [test_sykdomspulslog.sh](https://github.com/raubreywhite/dashboards_control/blob/master/bin/test_sykdomspulslog.sh)
- [test_sykdomspulspdf.sh](https://github.com/raubreywhite/dashboards_control/blob/master/bin/test_sykdomspulspdf.sh)

## Unit Testing - travis-ci {#travis}

[Travis-ci](http://travis-ci.org/folkehelseinstituttet) is used for  [unit testing of packages](http://r-pkgs.had.co.nz/check.html#travis). If the R package passes all tests, then we use [drat](https://github.com/eddelbuettel/drat) to deploy a built version of the package to Folkehelseinstituttet's R repository: https://folkehelseinstituttet.github.io/drat/.

